### ISSUE TITLE
Error when running the project

### ISSUE THREAD

**Issue by lisichka999** [Pudge601/extjs-replace-callparent#5]
Hi Martin, according to manual guide your library can solve some problems we have in our code with  caller method.
But when I run it in my project (just created a test project with all files I want to rewrite) in the following way:

![image](https://github.com/Pudge601/extjs-replace-callparent/assets/44223548/fca25b8e-833c-4548-9695-89899d5fc6ad)

**package.json**

{
  "name": "extremovecallparent",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "babel": "./node_modules/.bin/babel src -d dist"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@babel/cli": "^7.23.4",
    "@babel/core": "^7.23.5",
    "@babel/preset-env": "^7.23.5",
    "extjs-replace-callparent": "^1.0.1"
  }
}

**.babelrc**

{
   "plugins": ["extjs-replace-callparent"]
}

v18.16.1
npm 9.7.1

Does your library works in latest npm/node versions? Are you familiar with this error?
Really appreciate you help,
Thanks

**Comment by lisichka999** [comment]
The error I receive is >
D:\Sources\extRemoveCallParent>npm run babel

> extremovecallparent@1.0.0 babel
> ./node_modules/.bin/babel src -d dist

'.' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Pudge601** [comment]
Hi @lisichka999, sorry I've taken so long to reply!

It looks like your problem may be the way you've defined the 'babel' script in your package.json. it looks like you're running on Windows, but that path is a Linux style relative path; see this StackOverflow for more info: https://stackoverflow.com/questions/66185466/npm-script-fails-is-not-recognized-as-an-internal-or-external-command

Also, as mentioned in the top answer of that post, you can reference any NPM installed binary directly without giving a path from those script definitions, thanks to NPM setting up the path for you as described here: https://docs.npmjs.com/cli/v9/using-npm/scripts#path

So it should work if you change the script to something like: "babel src -d dist"
Although I'm not at a computer at the moment, so I haven't tested this myself. Hope this helped though!
